### ISSUE TITLE
Crash on dedicated server startup

### ISSUE THREAD

**Issue by magneticflux-** [magneticflux-/fabric-tree-chopper#61]
Reported by `mykehdoom` [here](https://www.curseforge.com/minecraft/mc-mods/fabric-tree-chopper?comment=67).

> Latest update is now crashing minecraft. at least on my server.
 ```
 java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-tree-chopper'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric_1.17.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric_1.17.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric_1.17.1.jar:?]
	at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric_1.17.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric_1.17.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric_1.17.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric_1.17.1.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric_1.17.1.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric_1.17.1.jar:?]
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/fiber2cloth/api/DefaultTypes
	at com.skaggsm.treechoppermod.FabricTreeChopper.onInitialize(FabricTreeChopper.kt:38) ~[fabric-tree-chopper-0.7.9.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric_1.17.1.jar:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.fiber2cloth.api.DefaultTypes
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric_1.17.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric_1.17.1.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at com.skaggsm.treechoppermod.FabricTreeChopper.onInitialize(FabricTreeChopper.kt:38) ~[fabric-tree-chopper-0.7.9.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric_1.17.1.jar:?]
	... 17 more
```

**Comment by magneticflux-** [comment]
Very strange. The file on Curseforge has the requested class present: `\fabric-tree-chopper-0.7.9.jar\META-INF\jars\fiber2cloth-3.2.0.jar\me\shedaniel\fiber2cloth\api\DefaultTypes.class`.

mykehdoom, what mod versions are you using? The full log file has the versions included.

**Comment by calloatti** [comment]
Same here:

```
[07:29:00] [main/INFO]: Loading for game Minecraft 1.17.1
[07:29:00] [ForkJoinPool-1-worker-9/WARN]: Non-Fabric mod JAR at "C:\MC-SERVER\mods\gravestone-1.17.1-1.0.4.jar", ignoring
[07:29:00] [ForkJoinPool-1-worker-11/WARN]: The mod "harvest" contains invalid entries in its mod json:
- Unsupported root entry "links" at line 7 column 10
[07:29:00] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[07:29:00] [main/WARN]: Warnings were found! 
 - Mod 'Beenfo' (beenfo) recommends version 1.1.7 or later of mod modupdater, which is missing!
	 - You must install version 1.1.7 or later of modupdater.
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b446313, also found 0.3.0+a02b4463d5, 0.3.0+a02b44633d, 0.3.0+a02b446318
 - Conflicting versions found for fabric-networking-v0: used 0.3.2+92519afad5, also found 0.3.2+92519afa18
 - Conflicting versions found for fabric-tool-attribute-api-v1: used 1.2.12+b7ab61213d, also found 1.2.12+b7ab612118
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.4+cbda931818, also found 1.0.4+a02b44633d
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.4.4+a02b44633d, also found 1.4.4+a02b446318
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+198a96213d, also found 1.0.4+cbda931818
 - Conflicting versions found for fabric-item-api-v1: used 1.2.4+a02b44633d, also found 1.2.4+cbda931818
[07:29:00] [main/WARN]: Mod `{}` ({}) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[07:29:00] [main/INFO]: [FabricLoader] Loading 125 mods:
	- alwaysawitherskull-fabric@1.4
	- amecsapi@1.1.4+mc21w16a
	- antiqueatlas@6.1.0-fabric-mc1.17.1
	- anvilrestoration-fabric@1.1
	- architectury@2.6.35
	- axesareweapons@1.3-1.17
	- basicshields@1.0.3+1.17.1
	- beenfo@1.17.1-fabric0.36.1-1.3.2
	- biom4st3r_repackaged_expressions@0.1.0
	- blue_endless_jankson@1.2.1
	- boatcontainer@1.0.3
	- caelus@0.0.18-1.17.1
	- cardinal-components-base@3.0.0
	- cardinal-components-entity@3.0.0
	- chalk@1.0.1
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.38
	- coat@1.0.0-beta.9
	- collective-fabric@1.61
	- colytra@2.0.0-1.17
	- com_electronwill_night-config_core@3.6.3
	- com_electronwill_night-config_toml@3.6.3
	- couplings@1.5.0+1.17
	- crowdin-translate@1.3+1.17
	- dismountentity-fabric@1.5
	- elytraboosters@1.2.0
	- elytratrinket@2.0.1-1.17
	- explorerscompass@1.17.1-2.0.2-fabric
	- fabric@0.41.0+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+cbda931818
	- fabric-biome-api-v1@3.2.0+cbda931818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+cbda931818
	- fabric-content-registries-v0@0.3.0+cbda931818
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.3.0+57bef5a318
	- fabric-events-interaction-v0@0.4.10+fc40aa9d18
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+cbda931818
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+cbda931818
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.5+kotlin.1.5.31
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+cbda931818
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afad5
	- fabric-object-builder-api-v1@1.10.9+cbda931818
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.11+7931163218
	- fabric-renderer-api-v1@0.4.4+cbda931818
	- fabric-renderer-indigo@0.4.8+cbda931818
	- fabric-renderer-registries-v1@3.2.4+7931163218
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.14+4658223018
	- fabric-rendering-v0@1.1.5+7931163218
	- fabric-rendering-v1@1.9.0+7931163218
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+198a96213d
	- fabric-screen-handler-api-v1@1.1.8+cbda931818
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b18
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabric-transfer-api-v1@1.4.0+7931163218
	- fabric-tree-chopper@0.7.9
	- fabricloader@0.11.7
	- fabricshieldlib@1.4.5+1.17
	- fiber@0.23.0-2
	- fiber2cloth@3.2.0
	- fixedanvilrepaircost-fabric@1.6
	- gbfabrictools@1.3.4+1.17
	- grindenchantments@1.4.0+1.17.1
	- gud_largebar@1.3.0
	- harvest@1.2.12
	- inventorysorter@1.8.0-1.17
	- java@16
	- kyrptconfig@1.1.10-1.17
	- libcd@3.0.3+1.16.3
	- magna@1.5.5-1.17-pre4
	- maybe-data@1.0.1-1.17
	- minecraft@1.17.1
	- modmenu@2.0.2
	- moenchant_lib@0.2.0
	- moenchantments@1.18.1
	- mousewheelie@1.7.3-newconfig+mc1.17.1-pre1
	- musketmod@1.4.1
	- naturescompass@1.17.1-2.0.1-fabric
	- noexpensive@1.17-Fabric-1.2.0
	- omega-config@1.0.4
	- org_jetbrains_kotlin_kotlin-reflect@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.31
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.31
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.2
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.2
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.3.0
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.3.0
	- overpoweredmending@2.2.4
	- particle_emitter_biom4st3r@0.1.0
	- ring_of_attraction@1.1.14
	- roughlyenoughitems@6.0.307-alpha
	- sign_editor@0.8.2
	- simple_backpack@1.1.19
	- slotlink@3.1.6
	- static-content@1.0.1-1.16.2
	- staticdata@1.1.2
	- trinkets@3.0.4
	- tweed4_annotated@1.0.0
	- tweed4_base@1.0.0
	- tweed4_data@1.0.0
	- tweed4_data_hjson@1.0.0
	- tweed4_tailor_coat@1.0.0
	- tweed4_tailor_screen@1.0.0
	- vanilla-hammers@3.1.2-1.17
	- wthit@3.10.0
[07:29:04] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/MC-SERVER/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[07:29:04] [main/INFO]: Compatibility level set to JAVA_16
[07:29:07] [main/WARN]: Reference map 'static-content-refmap.json' for static-content.mixins.json could not be read. If this is a development environment you can ignore this message
[07:29:07] [main/WARN]: Reference map 'RingOfAttraction-Fabric-1.17.1-refmap.json' for ring_of_attraction.mixins.json could not be read. If this is a development environment you can ignore this message
[07:29:07] [main/WARN]: Error loading class: net/minecraft/class_471 (java.lang.ClassNotFoundException: net/minecraft/class_471)
[07:29:07] [main/WARN]: @Mixin target net.minecraft.class_471 was not found noexpensive.mixins.json:AnvilScreenMixin
[07:29:07] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[07:29:07] [main/WARN]: Error loading class: net/minecraft/class_481 (java.lang.ClassNotFoundException: net/minecraft/class_481)
[07:29:07] [main/WARN]: @Mixin target net.minecraft.class_481 was not found trinkets.mixins.json:CreativeInventoryScreenMixin
[07:29:09] [main/WARN]: @ModifyVariable(@At("INVOKE")) Shift.BY=2 on biom4st3r_moenchantments.json:filterfeeder/LivingEntityMxn::localvar$zfl000$moenchantment$replaceItemFromFilterFeeder exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[07:29:09] [main/WARN]: @ModifyVariable(@At("FIELD")) Shift.BY=1 on moenchant_lib.json:events/LivingEntityDamageMxn::localvar$zif000$extendedEnchantment$modifyDamage2 exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[07:29:12] [main/WARN]: @Inject(@At("INVOKE_ASSIGN")) Shift.BY=2 on biom4st3r_moenchantments.json:soulbound/PlayerInventoryMxn::handler$zfa000$biom4st3r_providerContext exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[07:29:12] [main/WARN]: @ModifyVariable(@At("INVOKE_ASSIGN")) Shift.BY=2 on biom4st3r_moenchantments.json:soulbound/PlayerInventoryMxn::localvar$zfa000$biom4st3r_checkInventoriesForSoulbound exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[07:29:13] [main/INFO]: Configuration has been loaded
[07:29:13] [main/INFO]: [STDOUT]: Loading Collective (Fabric) version 1.61.
[07:29:13] [main/INFO]: Discovered plugin waila:core at mcp.mobius.waila.plugin.core.WailaCore
[07:29:14] [main/INFO]: Discovered plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[07:29:14] [main/INFO]: Registering plugin at mcp.mobius.waila.plugin.core.WailaCore
[07:29:14] [main/INFO]: Registering plugin at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[07:29:14] [main/INFO]: Plugin config reloaded
[07:29:14] [main/INFO]: [STDOUT]: Hello NoExpensive world!
[07:29:14] [main/INFO]: Fabric Shield Lib Initialized!
[07:29:14] [main/INFO]: [Grind Enchantments] Reading config.
[07:29:15] [main/INFO]: Loaded 14 Static Content files for vanilla-hammers:hammers
[07:29:15] [main/INFO]: Better Signs & Frames Initializing
[07:29:15] [main/INFO]: Basic Shields initialized!
[07:29:15] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zjb000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[07:29:15] [main/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[07:29:15] [main/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[07:29:15] [main/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[07:29:15] [main/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[07:29:15] [main/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[07:29:15] [main/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[07:29:15] [main/INFO]: [STDOUT]: net.minecraft.class_2248
[07:29:16] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'fabric-tree-chopper'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:33) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/fiber2cloth/api/DefaultTypes
	at com.skaggsm.treechoppermod.FabricTreeChopper.onInitialize(FabricTreeChopper.kt:38) ~[fabric-tree-chopper-0.7.9.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.fiber2cloth.api.DefaultTypes
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.server.InjectingURLClassLoader.loadClass(InjectingURLClassLoader.java:57) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:175) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at com.skaggsm.treechoppermod.FabricTreeChopper.onInitialize(FabricTreeChopper.kt:38) ~[fabric-tree-chopper-0.7.9.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-server-launch.jar:?]
	... 17 more
```
